#!/bin/bash
source venv/bin/activate           # 가상 환경 활성화

pip3 install -r requirements.txt   # 파이썬 디펜던시 설치
npm install                        # npm 디펜던시 설치
npm run release                    # Webpack 릴리즈용 빌드

sudo service hjlog restart           # 프로덕션 서버 시작
