"""empty message

Revision ID: 1160f38ab91
Revises: None
Create Date: 2015-08-20 05:01:19.963510

"""

# revision identifiers, used by Alembic.
revision = '1160f38ab91'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    pass
    ### end Alembic commands ###
