"""empty message

Revision ID: 3255e6bed08
Revises: 46ae0d2b68d
Create Date: 2015-12-31 22:35:01.740168

"""

# revision identifiers, used by Alembic.
revision = '3255e6bed08'
down_revision = '46ae0d2b68d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comment')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comment',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=30), autoincrement=False, nullable=True),
    sa.Column('ip', sa.VARCHAR(length=20), autoincrement=False, nullable=True),
    sa.Column('body', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('datetime', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('original_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['original_id'], ['post.id'], name='comment_original_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='comment_pkey')
    )
    ### end Alembic commands ###
