"""empty message

Revision ID: 3c82d9e20c5
Revises: 872ce9a655
Create Date: 2015-09-21 17:58:46.861227

"""

# revision identifiers, used by Alembic.
revision = '3c82d9e20c5'
down_revision = '872ce9a655'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('author_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'user', ['author_id'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'author_id')
    ### end Alembic commands ###
